version: '3'
services:
  iwatealle_middleman:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec middleman server
    env_file:
    - ./.env.dev
    volumes:
    - .:/app
    - data:/usr/local/bundle
    ports:
    - 4567:4567
    - 35729:35729
    tty: true
    stdin_open: true
    networks:
      selenium_hub:
        ipv4_address: 172.20.0.100
volumes:
  data:
networks:
  selenium_hub:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.0/24
