name: Build

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.19.1'
      - name: yarn install
        run: yarn install --frozen-lockfile
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.7'
      - name: bundle install
        run: bundle install
      - name: build
        run: |
          bundle exec middleman build --verbose
